-- Disposable local PostgreSQL only. Timers are local and have no server API.
\set ON_ERROR_STOP on
begin;
create function pg_temp.assert_true(value boolean,message text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'assertion failed: %',message; end if; end$$;
create function pg_temp.expect_error(command text,expected text) returns void language plpgsql as $$declare actual text; begin begin execute command; exception when others then get stacked diagnostics actual=returned_sqlstate; end; if actual is distinct from expected then raise exception 'expected SQLSTATE %, got %',expected,actual; end if; end$$;
select pg_temp.assert_true(public.notification_config()->>'nativeReady'='false','native push remains unavailable before Firebase provisioning');
select pg_temp.assert_true(public.notification_valid_subscription(jsonb_build_object('type','fcm','token',repeat('A',40),'installationProof',repeat('A',43))),'native token and installation proof accepted');
select pg_temp.assert_true(not public.notification_valid_subscription(jsonb_build_object('type','fcm','token',repeat('A',39),'installationProof',repeat('A',43))),'short native token rejected');
select pg_temp.assert_true(not public.notification_valid_subscription(jsonb_build_object('type','fcm','token','https://evil.example/'||repeat('A',40),'installationProof',repeat('A',43))),'native descriptor cannot supply an HTTP endpoint');
select pg_temp.assert_true(to_regprocedure('public.save_notification_timer(uuid,text,bigint,timestamptz)') is null,'local timers expose no server scheduling API');
select pg_temp.assert_true(to_regclass('public.notification_timer_state') is null,'local timers persist no server state');
insert into auth.users(id) values ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');
insert into public.user_roles(user_id,role) values ('00000000-0000-0000-0000-000000000003','professional');
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000001';
select pg_temp.assert_true(public.notification_config()->>'ready'='false','schema starts unprovisioned');
select pg_temp.expect_error($q$select * from public.notification_devices$q$,'42501');
select pg_temp.expect_error($q$select public.claim_notification_jobs(25)$q$,'42501');
select pg_temp.expect_error($q$select public.register_notification_device('90000000-0000-0000-0000-000000000001','{"endpoint":"https://127.0.0.1/a","keys":{"p256dh":"bad","auth":"bad"}}','{}','UTC','en','{}')$q$,'22023');
select public.register_notification_device('90000000-0000-0000-0000-000000000001',jsonb_build_object('endpoint','https://fcm.googleapis.com/test','keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth',repeat('A',22))),'{"weightReminder":true,"rest":false,"timedSet":false}','UTC','en','{}');
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';
select pg_temp.expect_error($q$select public.set_notification_presence('90000000-0000-0000-0000-000000000001',true)$q$,'42501');
select pg_temp.expect_error($q$select public.disable_notification_device('90000000-0000-0000-0000-000000000001')$q$,'42501');
select pg_temp.expect_error($q$select public.register_notification_device('90000000-0000-0000-0000-000000000001',jsonb_build_object('endpoint','https://fcm.googleapis.com/attacker','keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth',repeat('A',22))),'{}','UTC','en','{}')$q$,'42501');
select pg_temp.expect_error($q$select public.register_notification_device('90000000-0000-0000-0000-000000000002',jsonb_build_object('endpoint','https://fcm.googleapis.com/test','keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth','AQ'||repeat('A',20))),'{}','UTC','en','{}')$q$,'42501');
reset role;
select pg_temp.assert_true((select not preferences ? 'rest' and not preferences ? 'timedSet' from public.notification_devices),'local timer preferences are stripped from server state');
select pg_temp.assert_true(public.notification_valid_subscription(jsonb_build_object('endpoint','https://web.push.apple.com/abc','keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth',repeat('A',22)))),'Apple endpoint accepted');
select pg_temp.assert_true(not public.notification_valid_subscription(jsonb_build_object('endpoint',bad,'keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth',repeat('A',22)))),'SSRF endpoint rejected') from unnest(array['https://push.apple.com.evil.test/a','https://evil.test@fcm.googleapis.com/a','https://fcm.googleapis.com:443/a','https://fcm.googleapis.com/a#x','https://updates.push.services.mozilla.com.evil/a','http://fcm.googleapis.com/a','https://fcm.googleapis.com/a b']) bad;
select pg_temp.assert_true(public.notification_effective_routine('{"planMode":"weekly","week":{"0":"r"},"dayPlan":{"2026-10-04":"missing"},"routines":[{"id":"r","hasExercises":true}]}','2026-10-04')='r','invalid override falls back weekly');
select pg_temp.assert_true(public.notification_effective_routine('{"planMode":"weekly","week":{"0":"r"},"dayPlan":{"2026-10-04":"rest"},"routines":[{"id":"r","hasExercises":true}]}','2026-10-04') is null,'rest day override wins');
select pg_temp.assert_true(public.notification_effective_routine('{"planMode":"daily","week":{"0":"r"},"routines":[{"id":"r","hasExercises":true}]}','2026-10-04') is null,'daily plan never falls back weekly');
select pg_temp.assert_true(public.notification_allowed_at('{"quietHours":{"enabled":true,"start":"22:00","end":"07:00"}}','America/New_York','2026-11-01 03:30:00+00')='2026-11-01 12:00:00+00','quiet hours use local date across DST');
select pg_temp.assert_true(jsonb_array_length(public.notification_schedule(jsonb_build_object('routines',(select jsonb_agg(jsonb_build_object('id',repeat('x',250)||i,'hasExercises',true)) from generate_series(1,2000) i)))->'routines')=2000,'valid backup preserves two thousand long routine identifiers');
select pg_temp.assert_true(not (public.notification_schedule('{"routines":[{"id":"r","hasExercises":true,"name":"Private routine"}]}')->'routines'->0 ? 'name'),'scheduler strips prescription names');
-- Account endpoint handoff requires subscription-key proof and cancels the old owner.
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at) select id,owner_id,subscription_revision,'old-owner','weight_reminder','/#/body-progress',current_date,now(),now()+interval '1 hour' from public.notification_devices;
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';
select public.register_notification_device('90000000-0000-0000-0000-000000000002',jsonb_build_object('endpoint','https://fcm.googleapis.com/test','keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth',repeat('A',22))),'{"weightReminder":true}','UTC','zh','{}');
reset role;
select pg_temp.assert_true((select count(*)=0 from public.notification_jobs where owner_id='00000000-0000-0000-0000-000000000001' and status in ('pending','claimed')),'endpoint handoff cancels old account work');
-- Foreground suppression, bounded claims and retry/410 compare-and-swap.
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at) select id,owner_id,subscription_revision,'lease-test','weight_reminder','/#/body-progress',current_date,now(),now()+interval '1 hour' from public.notification_devices;
set local role authenticated;
select public.set_notification_presence('90000000-0000-0000-0000-000000000002',true);
reset role;
select pg_temp.assert_true((select foreground_until between now()+interval '64 seconds' and now()+interval '66 seconds' from public.notification_devices),'visible lease lasts sixty-five seconds');
select pg_temp.assert_true(public.claim_notification_jobs(25)='[]','foreground lease suppresses remote push');
update public.notification_devices set foreground_until=null;
update public.notification_jobs set due_at=now() where event_key='lease-test';
create temporary table claim as select public.claim_notification_jobs(25)->0 payload;
select pg_temp.assert_true((select payload->>'kind'='weight_reminder' and not payload ? 'timerRevision' from claim),'claim contains reminder without timer metadata');
select pg_temp.assert_true((select claimed_until between now()+interval '119 seconds' and now()+interval '121 seconds' from public.notification_jobs where id=(select (payload->>'id')::uuid from claim)),'lease covers bounded worker batch');
select pg_temp.assert_true(public.claim_notification_jobs(25)='[]','unexpired claim cannot repeat');
update public.notification_jobs set claimed_until=now()-interval '1 millisecond' where event_key='lease-test';
select pg_temp.assert_true((select not public.confirm_notification_job((payload->>'id')::uuid,(payload->>'claimToken')::uuid,'sent',201) from claim),'expired worker cannot acknowledge delivery');
create temporary table reclaimed as select public.claim_notification_jobs(25)->0 payload;
select pg_temp.assert_true((select not public.notification_job_is_current((payload->>'id')::uuid,(payload->>'claimToken')::uuid) from claim),'old token invalid after recovery');
select pg_temp.assert_true((select public.notification_job_is_current((payload->>'id')::uuid,(payload->>'claimToken')::uuid) from reclaimed),'new token current after recovery');
select public.confirm_notification_job((payload->>'id')::uuid,(payload->>'claimToken')::uuid,'cancelled',null) from reclaimed;
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at) select id,owner_id,subscription_revision,'retry-test','weight_reminder','/#/body-progress',current_date,now(),now()+interval '1 hour' from public.notification_devices;
do $$declare payload jsonb; attempt integer; begin for attempt in 1..5 loop update public.notification_jobs set due_at=now() where event_key='retry-test'; payload:=public.claim_notification_jobs(25)->0; perform pg_temp.assert_true(payload is not null,'retry has a claim'); perform pg_temp.assert_true(public.notification_job_is_current((payload->>'id')::uuid,(payload->>'claimToken')::uuid),'fifth attempt remains valid'); perform public.confirm_notification_job((payload->>'id')::uuid,(payload->>'claimToken')::uuid,'retry',503); end loop; perform pg_temp.assert_true(public.claim_notification_jobs(25)='[]','sixth attempt refused'); perform pg_temp.assert_true((select status='failed' and attempts=5 from public.notification_jobs where event_key='retry-test'),'retry budget exhausted'); end$$;
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at) select id,owner_id,subscription_revision,'web-unauthorized','weight_reminder','/#/body-progress',current_date,now(),now()+interval '1 hour' from public.notification_devices;
truncate claim; insert into claim select public.claim_notification_jobs(25)->0;
select public.confirm_notification_job((payload->>'id')::uuid,(payload->>'claimToken')::uuid,'retry',401) from claim;
select pg_temp.assert_true((select status='failed' from public.notification_jobs where event_key='web-unauthorized'),'Web Push authorization failure is fatal');
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at) select id,owner_id,subscription_revision,'subscription-test','weight_reminder','/#/body-progress',current_date,now(),now()+interval '1 hour' from public.notification_devices;
truncate claim; insert into claim select public.claim_notification_jobs(25)->0;
set local role authenticated;
select public.register_notification_device('90000000-0000-0000-0000-000000000002',jsonb_build_object('endpoint','https://fcm.googleapis.com/test','keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth','AQ'||repeat('A',20))),'{"weightReminder":true}','UTC','en','{}');
reset role;
select pg_temp.assert_true((select not public.confirm_notification_job((payload->>'id')::uuid,(payload->>'claimToken')::uuid,'invalid',410) from claim),'stale 410 cannot disable renewed subscription');
select pg_temp.assert_true((select enabled from public.notification_devices),'renewed subscription stays enabled');
-- Fourteen local-date horizon and records, with future overrides retained for refill.
set local role authenticated;
select public.register_notification_device('90000000-0000-0000-0000-000000000002',jsonb_build_object('endpoint','https://fcm.googleapis.com/test','keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth',repeat('A',22))),'{"workoutReminder":true,"weightReminder":true,"measurementReminder":true}','America/Sao_Paulo','pt',jsonb_build_object('week',jsonb_build_object('0','r','1','r','2','r','3','r','4','r','5','r','6','r'),'routines','[{"id":"r","hasExercises":true}]'::jsonb,'completedDates',jsonb_build_array(to_char((now() at time zone 'America/Sao_Paulo')::date+1,'YYYY-MM-DD')),'activeDate',to_char((now() at time zone 'America/Sao_Paulo')::date+2,'YYYY-MM-DD'),'dayPlan',jsonb_build_object(to_char((now() at time zone 'America/Sao_Paulo')::date+20,'YYYY-MM-DD'),'rest')));
reset role;
select pg_temp.assert_true((select count(*) between 10 and 14 from public.notification_jobs where kind='workout_reminder' and status='pending'),'workout horizon is bounded');
select pg_temp.assert_true((select count(*)=0 from public.notification_jobs where kind='workout_reminder' and status='pending' and local_date in ((now() at time zone 'America/Sao_Paulo')::date+1,(now() at time zone 'America/Sao_Paulo')::date+2)),'active and completed dates skipped');
select pg_temp.assert_true((select max(local_date)<=(now() at time zone 'America/Sao_Paulo')::date+13 from public.notification_jobs where status='pending'),'no job beyond fourteen local dates');
update public.notification_devices set expanded_local_date=(now() at time zone timezone)::date-1;
select public.notification_maintenance();
select pg_temp.assert_true((select public.notification_effective_routine(schedule,(now() at time zone timezone)::date+20) is null and schedule->'dayPlan' ? to_char((now() at time zone timezone)::date+20,'YYYY-MM-DD') from public.notification_devices),'refill retains future weekly rest override');
select pg_temp.assert_true(public.notification_effective_routine(public.notification_schedule(jsonb_build_object('planMode','daily','dayPlan',jsonb_build_object(to_char(current_date+20,'YYYY-MM-DD'),'r'),'routines','[{"id":"r","hasExercises":true}]'::jsonb)),current_date+20)='r','future daily plan remains available for later refill');
update public.notification_devices set schedule=jsonb_set(jsonb_set(schedule,'{weightDates}','["2026-10-07"]'),'{measurementWeeks}','["2026-10-05"]');
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at)
select id,owner_id,subscription_revision,k,k,'/#/body-progress','2026-10-11',now(),now()+interval '1 hour' from public.notification_devices cross join unnest(array['weight_reminder','measurement_reminder']) k;
select pg_temp.assert_true(public.claim_notification_jobs(25)='[]','recorded check-in periods suppress due weight and measurement jobs');
select pg_temp.assert_true((select count(*)=2 from public.notification_jobs where local_date='2026-10-11' and event_key in ('weight_reminder','measurement_reminder') and status='cancelled'),'Monday week records suppress the following Sunday check-in');
update public.notification_devices set schedule=jsonb_set(jsonb_set(schedule,'{weightDates}','[]'),'{measurementWeeks}','[]');
update public.notification_jobs set local_due_at=now(),due_at=now()+interval '65 seconds' where kind='weight_reminder' and status='pending';
set local role authenticated;
select pg_temp.assert_true(exists(select 1 from jsonb_array_elements(public.set_notification_presence('90000000-0000-0000-0000-000000000002',true)) e where e->>'kind'='weight_reminder'),'locally due reminder remains readable while remote delivery deferred');
select public.consume_notification_events('90000000-0000-0000-0000-000000000002',array(select (e->>'id')::uuid from jsonb_array_elements(public.read_notification_events('90000000-0000-0000-0000-000000000002')) e));
reset role;
select pg_temp.assert_true((select count(*)>0 from public.notification_jobs where kind='weight_reminder' and status='delivered_local'),'local acknowledgement prevents push replay');
-- All professional event branches use authoritative rows and generic navigation.
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000003';
select public.register_notification_device('90000000-0000-0000-0000-000000000003',jsonb_build_object('endpoint','https://fcm.googleapis.com/professional','keys',jsonb_build_object('p256dh','B'||repeat('A',86),'auth',repeat('A',22))),'{}','UTC','en','{}');
reset role;
insert into public.professional_profiles(user_id,professional_name) values ('00000000-0000-0000-0000-000000000003','Professional');
set local role authenticated;
set local request.jwt.claim.role='service_role';
select pg_temp.expect_error($q$update public.professional_profiles set verification_status='verified' where user_id=auth.uid()$q$,'42501');
reset role;
set local role service_role;
set local request.jwt.claim.sub='';
update public.professional_profiles set verification_status='verified' where user_id='00000000-0000-0000-0000-000000000003';
update public.professional_profiles set verification_status='verified' where user_id='00000000-0000-0000-0000-000000000003';
reset role;
select pg_temp.assert_true((select count(*)=1 from public.notification_events where kind='verification_changed'),'server verification emits once; forged JWT does not grant privilege');
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000003';
insert into public.professional_student_relationships(id,professional_user_id,student_user_id) values ('10000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000003','00000000-0000-0000-0000-000000000002');
select pg_temp.assert_true((select count(*)=1 from public.notification_events where kind='relationship_accepted' and owner_id='00000000-0000-0000-0000-000000000002'),'accepted relationship notifies counterpart');
select pg_temp.assert_true((select count(*)=0 from public.notification_events where kind='relationship_accepted' and owner_id='00000000-0000-0000-0000-000000000003'),'actor receives no own relationship push');
insert into public.programs(id,professional_user_id,title) values ('20000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000003','Private');
insert into public.program_versions(id,program_id,version_number,weekly_plan,published_at) values ('30000000-0000-0000-0000-000000000001','20000000-0000-0000-0000-000000000001',1,'{"monday":[{"exerciseId":"x","sets":3,"reps":10}]}',now()),('30000000-0000-0000-0000-000000000002','20000000-0000-0000-0000-000000000001',2,'{"monday":[{"exerciseId":"x","sets":4,"reps":10}]}',now());
set local role authenticated;
select public.assign_program_version('20000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002');
select public.assign_program_version('20000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000002');
reset role; set constraints all immediate;
select pg_temp.assert_true((select count(*)=0 from public.notification_events where kind='program_removed'),'replacement coalesces false removal');
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';
select pg_temp.assert_true(exists(select 1 from jsonb_array_elements(public.read_notification_events('90000000-0000-0000-0000-000000000002')) e where e->>'kind'='program_updated'),'published assignment emits a current generic program event');
select public.consume_notification_events('90000000-0000-0000-0000-000000000002',array(select (e->>'id')::uuid from jsonb_array_elements(public.read_notification_events('90000000-0000-0000-0000-000000000002')) e));
select public.start_workout_execution('40000000-0000-0000-0000-000000000001',(select id from public.program_assignments where status='active'),'monday');
reset role;
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at) select id,owner_id,subscription_revision,'workout-authority','workout_reminder','/#/workout',(now() at time zone timezone)::date,now(),now()+interval '1 hour' from public.notification_devices where owner_id='00000000-0000-0000-0000-000000000002';
select pg_temp.assert_true((select not public.notification_job_eligible(j) from public.notification_jobs j where event_key='workout-authority'),'authoritative active execution suppresses stale calendar reminder');
set local role authenticated;
select public.complete_workout_execution('40000000-0000-0000-0000-000000000001');
select public.complete_workout_execution('40000000-0000-0000-0000-000000000001');
select public.start_workout_execution('40000000-0000-0000-0000-000000000002',(select id from public.program_assignments where status='active'),'monday');
select public.abandon_workout_execution('40000000-0000-0000-0000-000000000002');
reset role;
select pg_temp.assert_true((select count(*)=1 from public.notification_events where kind='student_workout_completed'),'completion replay emits once');
select pg_temp.assert_true((select count(*)=1 from public.notification_events where kind='student_workout_abandoned'),'abandonment emits once');
select pg_temp.assert_true((select count(*)=0 from public.notification_events where kind in ('student_workout_completed','student_workout_abandoned') and owner_id='00000000-0000-0000-0000-000000000002'),'student actor receives no own push');
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000003';
select public.revoke_program_assignment((select id from public.program_assignments where status='active'));
reset role;
select pg_temp.assert_true((select count(*)=1 from public.notification_events where kind='program_removed'),'real removal emits once');
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';
select public.revoke_professional_relationship('10000000-0000-0000-0000-000000000001');
reset role;
select pg_temp.assert_true((select count(*)=0 from public.notification_jobs j join public.notification_events e on e.id=j.event_id where e.relationship_id='10000000-0000-0000-0000-000000000001' and e.kind<>'relationship_ended' and j.status in ('pending','claimed')),'relationship revocation cancels stale professional deliveries');
select pg_temp.assert_true((select count(*)=1 from public.notification_events where kind='relationship_ended'),'counterpart receives ended event despite revoked relation');
set local role authenticated;
select public.disable_notification_device('90000000-0000-0000-0000-000000000002');
reset role;
select pg_temp.assert_true((select count(*)=0 from public.notification_jobs where owner_id='00000000-0000-0000-0000-000000000002' and status in ('pending','claimed')),'disable cancels only owned device work');
select pg_temp.assert_true((select count(*)=1 from public.notification_jobs where owner_id='00000000-0000-0000-0000-000000000003' and status='pending' and kind='relationship_ended'),'other account event survives disable');
select pg_temp.assert_true((select bool_and(href like '/#/%') from public.notification_jobs),'server routes match HashRouter');
-- Native account handoff uses the installation proof, never the public device UUID.
update public.notification_jobs set status='cancelled',claim_token=null,claimed_until=null where status in ('pending','claimed');
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000001';
select pg_temp.expect_error($q$select public.register_notification_device('91000000-0000-0000-0000-000000000001',jsonb_build_object('type','fcm','token',repeat('A',40),'installationProof',repeat('A',43)),'{}','UTC','en','{}')$q$,'42501');
reset role;
update public.notification_settings set native_ready=true;
set local role authenticated;
select public.register_notification_device('91000000-0000-0000-0000-000000000001',jsonb_build_object('type','fcm','token',repeat('A',40),'installationProof',repeat('A',43)),'{"weightReminder":true}','UTC','en','{}');
reset role;
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at) select id,owner_id,subscription_revision,'native-old-owner','weight_reminder','/#/body-progress',current_date,now(),now()+interval '1 hour' from public.notification_devices where transport='fcm';
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';
select pg_temp.expect_error($q$select public.register_notification_device('91000000-0000-0000-0000-000000000001',jsonb_build_object('type','fcm','token',repeat('B',40),'installationProof',repeat('A',43)),'{}','UTC','en','{}')$q$,'42501');
select pg_temp.expect_error($q$select public.register_notification_device('91000000-0000-0000-0000-000000000002',jsonb_build_object('type','fcm','token',repeat('A',40),'installationProof','AQ'||repeat('A',41)),'{}','UTC','en','{}')$q$,'42501');
select public.register_notification_device('91000000-0000-0000-0000-000000000002',jsonb_build_object('type','fcm','token',repeat('A',40),'installationProof',repeat('A',43)),'{"weightReminder":true}','UTC','en','{}');
select public.register_notification_device('92000000-0000-0000-0000-000000000002',jsonb_build_object('type','fcm','token',(select string_agg(md5(i::text),'') from generate_series(1,128) i),'installationProof',repeat('A',43)),'{}','UTC','en','{}');
reset role;
select pg_temp.assert_true((select char_length(endpoint)=4100 from public.notification_devices where device_key='92000000-0000-0000-0000-000000000002'),'maximum-length native token fits durable endpoint uniqueness');
select pg_temp.assert_true((select count(*)=0 from public.notification_jobs where event_key='native-old-owner' and status in ('pending','claimed')),'native handoff cancels old account delivery');
insert into public.notification_jobs(device_id,owner_id,subscription_revision,event_key,kind,href,local_date,due_at,expires_at) select id,owner_id,subscription_revision,'native-claim','weight_reminder','/#/body-progress',current_date,now(),now()+interval '1 hour' from public.notification_devices where device_key='91000000-0000-0000-0000-000000000002';
select pg_temp.assert_true(public.claim_notification_jobs(25,false)='[]','worker without Firebase skips native transport');
update public.notification_settings set native_ready=false;
select pg_temp.assert_true(public.claim_notification_jobs(25,true)='[]','worker cannot override disabled native server capability');
update public.notification_settings set native_ready=true;
truncate claim; insert into claim select public.claim_notification_jobs(25,true)->0;
select pg_temp.assert_true((select payload->'subscription'->>'type'='fcm' and payload->'subscription'->>'token'=repeat('A',40) from claim),'native worker receives the token descriptor without fetching it as a URL');
select public.confirm_notification_job((payload->>'id')::uuid,(payload->>'claimToken')::uuid,'retry',401) from claim;
select pg_temp.assert_true((select status='pending' and attempts=1 and due_at=now()+interval '5 seconds' from public.notification_jobs where event_key='native-claim'),'FCM OAuth expiration gets one bounded refresh retry');
update public.notification_jobs set due_at=now() where event_key='native-claim';
truncate claim; insert into claim select public.claim_notification_jobs(25,true)->0;
select public.confirm_notification_job((payload->>'id')::uuid,(payload->>'claimToken')::uuid,'invalid',400) from claim;
select pg_temp.assert_true((select not enabled from public.notification_devices where device_key='91000000-0000-0000-0000-000000000002'),'FCM UNREGISTERED400 disables current native token');
select pg_temp.assert_true((select enabled from public.notification_devices where device_key='92000000-0000-0000-0000-000000000002'),'native invalidation preserves another registered device');
rollback;
