select has_table('public', 'professional_student_relationships', 'professional/student relationships exist');
select has_table('public', 'professional_invites', 'professional invites exist');
select has_table('public', 'programs', 'program identities exist');
select has_table('public', 'program_versions', 'immutable program versions exist');
select has_table('public', 'program_assignments', 'program assignments exist');
select has_table('public', 'workout_executions', 'workout executions exist');
select ok((select relrowsecurity from pg_class where oid = 'public.professional_student_relationships'::regclass), 'relationships have RLS');
select ok((select relrowsecurity from pg_class where oid = 'public.programs'::regclass), 'programs have RLS');
select ok(has_function_privilege('authenticated', 'public.accept_professional_invite(text)', 'EXECUTE'), 'students can accept invites through RPC');
select ok(not has_function_privilege('anon', 'public.accept_professional_invite(text)', 'EXECUTE'), 'anonymous users cannot accept invites');
select ok(has_function_privilege('authenticated', 'public.create_professional_invite(public.invite_kind)', 'EXECUTE'), 'professionals can create invites through RPC');
select ok(not has_function_privilege('anon', 'public.create_professional_invite(public.invite_kind)', 'EXECUTE'), 'anonymous users cannot create invites');
select ok((select prosecdef from pg_proc where oid = 'public.accept_professional_invite(text)'::regprocedure), 'invite acceptance is SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid = 'public.create_professional_invite(public.invite_kind)'::regprocedure), 'invite creation is SECURITY DEFINER');
