// @vitest-environment happy-dom
import React, { act } from 'react'
import { createRoot } from 'react-dom/client'
import { MemoryRouter, Routes, Route, Link, useLocation } from 'react-router-dom'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ auth: {}, repo: { previewInvite: vi.fn(), acceptInvite: vi.fn() } }))
vi.mock('../auth/AuthProvider.jsx', () => ({ useAuth: () => mocks.auth }))
vi.mock('../lib/supabase-client.js', () => ({ getBrowserSupabaseClient: () => ({ storage: { from: () => ({ getPublicUrl: path => ({ data: { publicUrl: `https://project.test/storage/v1/object/public/professional-photos/${path}` } }) }) } }) }))
vi.mock('../lib/professional-workflow.js', () => ({ createProfessionalWorkflowRepository: () => mocks.repo }))
import StudentProfessionalInvite from './StudentProfessionalInvite.jsx'
let root, container
it('shows the professional photo in the invite preview', async () => {
  const photo_path = '11111111-1111-4111-8111-111111111111/22222222-2222-4222-8222-222222222222.jpg'
  mocks.repo.previewInvite.mockResolvedValue([{ professional_name: 'Ana', photo_path }]); await render()
  expect(container.querySelector('.management-avatar img')?.getAttribute('src')).toContain(photo_path)
})
beforeEach(() => { vi.clearAllMocks(); mocks.auth = { status: 'authenticated', user: { id: 's1' } }; mocks.repo.previewInvite.mockResolvedValue([{ professional_name: 'Ana Silva' }]); mocks.repo.acceptInvite.mockResolvedValue({}); container = document.createElement('div'); document.body.append(container); root = createRoot(container) })
afterEach(async () => { await act(async () => root.unmount()); container.remove() })
function Destination() { const { search } = useLocation(); return <p>Overview {search}</p> }
const render = async (path = '/student/professionals/add?code=AB12') => act(async () => root.render(<MemoryRouter initialEntries={[path]}><Link to="/student/professionals/add?code=CD34">Other code</Link><Routes><Route path="/student/professionals/add" element={<StudentProfessionalInvite />} /><Route path="/student/professionals" element={<Destination />} /></Routes></MemoryRouter>))
it('previews the code-bearing add route and requires explicit acceptance', async () => { await render(); expect(mocks.repo.previewInvite).toHaveBeenCalledWith('AB12'); expect(container.textContent).toContain('Ana Silva'); expect(mocks.repo.acceptInvite).not.toHaveBeenCalled(); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Vincular a este profissional').click()); expect(mocks.repo.acceptInvite).toHaveBeenCalledWith('AB12'); expect(container.textContent).toContain('Overview ?invite=accepted') })
it('locks acceptance immediately against repeated clicks', async () => { let resolve; mocks.repo.acceptInvite.mockReturnValue(new Promise(r => { resolve = r })); await render(); const button = [...container.querySelectorAll('button')].find(x => x.textContent === 'Vincular a este profissional'); await act(async () => { button.click(); button.click() }); expect(mocks.repo.acceptInvite).toHaveBeenCalledTimes(1); expect(container.textContent).toContain('Vinculando…'); await act(async () => resolve({})) })
it('discards delayed previews when the query code changes', async () => { let resolve; mocks.repo.previewInvite.mockReturnValueOnce(new Promise(r => { resolve = r })); await render(); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Other code').click()); await act(async () => resolve([{ professional_name: 'Stale professional' }])); expect(container.textContent).not.toContain('Stale professional'); expect(container.querySelector('input').value).toBe('CD34') })
it('does not navigate after accepting an earlier query code', async () => { let resolve; mocks.repo.acceptInvite.mockReturnValueOnce(new Promise(r => { resolve = r })); await render(); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Vincular a este profissional').click()); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Other code').click()); await act(async () => resolve({})); expect(container.textContent).not.toContain('Overview ?invite=accepted'); expect(container.querySelector('input').value).toBe('CD34') })
it('clears a delayed account preview and has an anonymous session guard', async () => { let resolve; mocks.repo.previewInvite.mockReturnValueOnce(new Promise(r => { resolve = r })); await render(); mocks.auth = { status: 'anonymous', user: null }; await render(); await act(async () => resolve([{ professional_name: 'Other account preview' }])); expect(container.textContent).not.toContain('Other account preview'); expect(container.textContent).toContain('Entre na sua conta para acessar seus profissionais.'); expect(container.textContent).not.toContain('Consultando convite…') })
it('finishes stalled authentication with a usable return path', async () => { mocks.auth = { status: 'initializing', user: null }; const timer = vi.spyOn(window, 'setTimeout').mockImplementation(fn => { fn(); return 1 }); await render(); expect(container.textContent).toContain('Não foi possível confirmar sua sessão. Tente novamente.'); expect(container.textContent).not.toContain('Consultando convite…'); expect(container.querySelector('a[href="/student/professionals"]')).not.toBeNull(); timer.mockRestore() })
it('shows a verified invite profile accurately', async () => { mocks.repo.previewInvite.mockResolvedValue([{ professional_name: 'Ana Silva', verification_status: 'verified' }]); await render(); expect(container.textContent).toContain('Verificação: Verificado') })
