// @vitest-environment happy-dom
import React, { act } from 'react'
import { createRoot } from 'react-dom/client'
import { beforeEach, afterEach, it, expect } from 'vitest'
import { useStore } from '../../../store/useStore.js'
import { useProgramDraft } from './useProgramDraft.js'
let root, node, api
const initialDraft = { title: 'Base', weeklyPlan: { monday: [{ exerciseId: '9997', sets: 3, reps: 8, load: 0, mode: 'cardio', min: 30, speed: 7, rest: 45, unit: 'lb', effort: 'rir', rir: 2, notes: 'Leve', sg: 'A' }] }, workoutTitles: { monday: 'Corrida' } }
function Probe(props) { api = useProgramDraft(props); return null }
const render = async (accountId = '11111111-1111-4111-8111-111111111111', programId = 'p') => act(async () => root.render(React.createElement(Probe, { accountId, programId, initialDraft })))
beforeEach(async () => { globalThis.IS_REACT_ACT_ENVIRONMENT = true; localStorage.clear(); await useStore.getState().activateLocalScope('11111111-1111-4111-8111-111111111111'); node = document.createElement('div'); document.body.append(node); root = createRoot(node) })
afterEach(async () => { await act(async () => root.unmount()); node.remove() })
it('draft_survives_day_navigation_and_reload', async () => { await render(); await act(async () => { api.setWorkoutTitle('tuesday', 'Força'); api.addExercise('tuesday', { id: '9998' }) }); await act(async () => root.unmount()); root = createRoot(node); await render(); expect(api.draft.workoutTitles.tuesday).toBe('Força'); expect(api.draft.weeklyPlan.tuesday).toHaveLength(1); expect(api.dirty).toBe(true) })
it('draft_never_crosses_accounts and stale callbacks cannot write', async () => { await render(); const old = api; await act(async () => old.updateMetadata({ title: 'A privado' })); await act(async () => useStore.getState().activateLocalScope('22222222-2222-4222-8222-222222222222')); await render('22222222-2222-4222-8222-222222222222'); await act(async () => old.updateMetadata({ title: 'Vazamento' })); expect(api.draft.title).toBe('Base'); expect(useStore.getState().S.professionalProgramDrafts['11111111-1111-4111-8111-111111111111:p']).toBeUndefined() })
it('copy_requires_overwrite_confirmation', async () => { await render(); await act(async () => api.addExercise('tuesday', { id: '9998' })); let outcome; await act(async () => { outcome = api.copyDay('monday', 'tuesday') }); expect(outcome).toBe('confirmation-required'); expect(api.draft.weeklyPlan.tuesday[0].exerciseId).toBe('9998'); await act(async () => api.copyDay('monday', 'tuesday', { overwrite: true })); expect(api.draft.workoutTitles.tuesday).toBe('Corrida') })
it('duplicate_and_move_preserve_prescription and reject stale revision targets', async () => { await render(); const stale = api.target('monday', 0); await act(async () => api.duplicateExercise('monday', stale)); await act(async () => api.updateExercise('monday', stale, { notes: 'Wrong' })); expect(api.draft.weeklyPlan.monday[0].notes).toBe('Leve'); await act(async () => api.moveExercise('monday', api.target('monday', 1), -1)); expect(api.draft.weeklyPlan.monday).toEqual([initialDraft.weeklyPlan.monday[0], initialDraft.weeklyPlan.monday[0]]) })
it('50 cap and invalid day reject mutations', async () => { await render(); await act(async () => { for (let i = 0; i < 60; i++) api.addExercise('tuesday', { id: String(i) }); api.addExercise('garbage', { id: 'bad' }) }); expect(api.draft.weeklyPlan.tuesday).toHaveLength(50); expect(api.draft.weeklyPlan.garbage).toBeUndefined() })
it('migrates legacy plan metadata without losing saved values', async () => { useStore.getState().update(s => { s.professionalProgramDrafts['11111111-1111-4111-8111-111111111111:p'] = { plan: initialDraft.weeklyPlan, metadata: { title: 'Recuperado', objective: 'Saúde' } } }); await render(); expect(api.draft.title).toBe('Recuperado'); expect(api.draft.weeklyPlan.monday[0]).toEqual(initialDraft.weeklyPlan.monday[0]); expect(useStore.getState().S.professionalProgramDrafts['11111111-1111-4111-8111-111111111111:p'].weeklyPlan.monday).toHaveLength(1) })
it('publication cannot clear a newer revision and effect flushing never recreates cleared drafts', async () => { await render(); const token = api.publicationToken(); await act(async () => api.updateMetadata({ title: 'Editado' })); expect(api.clearAfterPublication(token)).toBe(false); expect(api.draft.title).toBe('Editado'); const valid = api.publicationToken(); await act(async () => { expect(api.clearAfterPublication(valid)).toBe(true) }); await render(); await act(async () => {}); expect(useStore.getState().S.professionalProgramDrafts['11111111-1111-4111-8111-111111111111:p']).toBeUndefined() })
it('A-B-A never revalidates old mutation callbacks', async () => { await render(); const stale = api; await act(async () => api.updateMetadata({ title: 'A salvo' })); await act(async () => useStore.getState().activateLocalScope('22222222-2222-4222-8222-222222222222')); await render('22222222-2222-4222-8222-222222222222'); await act(async () => useStore.getState().activateLocalScope('11111111-1111-4111-8111-111111111111')); await render(); await act(async () => stale.updateMetadata({ title: 'Antigo' })); expect(api.draft.title).toBe('A salvo') })
