import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider.jsx'
import { getBrowserSupabaseClient } from '../lib/supabase-client.js'
import { createProfessionalWorkflowRepository } from '../lib/professional-workflow.js'
import { statusLabel } from '../lib/professional-ux.js'
import { Button, Section } from '../components/ui.jsx'
import AppHeader from '../components/AppHeader.jsx'
import ProfessionalWorkspaceNav from '../components/ProfessionalWorkspaceNav.jsx'

const TABS = [['summary', 'Resumo'], ['training', 'Treino'], ['history', 'Histórico'], ['relationship', 'Vínculo']]

export default function ProfessionalStudentPage() {
  const auth = useAuth(); const navigate = useNavigate(); const { studentId } = useParams(); const repo = useMemo(() => createProfessionalWorkflowRepository({ client: getBrowserSupabaseClient() }), [])
  const [client, setClient] = useState(null); const [detail, setDetail] = useState(null); const [versions, setVersions] = useState([]); const [tab, setTab] = useState('summary'); const [versionId, setVersionId] = useState(''); const [busy, setBusy] = useState(true); const [error, setError] = useState(''); const [confirmRevoke, setConfirmRevoke] = useState(false)
  const refresh = async () => { setBusy(true); setError(''); try { const [summaries, nextDetail, relationships, programs] = await Promise.all([repo.clientSummaries(), repo.clientDetail(studentId), repo.relationships(auth.user.id), repo.programs()]); const pairs = await Promise.all(programs.map(async program => repo.versions(program.id))); setClient(summaries.find(item => item.studentUserId === studentId) || { studentUserId: studentId, displayName: nextDetail?.displayName || 'Aluno' }); setDetail({ ...nextDetail, relationship: relationships.find(item => item.student_user_id === studentId && item.status === 'active') || null }); setVersions(pairs.flat()) } catch { setError('Não foi possível carregar este aluno.') } finally { setBusy(false) } }
  useEffect(() => { if (auth.user?.id && studentId) refresh() }, [auth.user?.id, studentId])
  const assign = async () => { const version = versions.find(item => item.id === versionId); if (!version) return; try { await repo.assignProgramVersion({ programId: version.program_id, versionId: version.id, studentUserId: studentId }); setVersionId(''); await refresh(); setError('') } catch { setError('Não foi possível enviar esta versão.') } }
  const revoke = async () => { const relationship = detail?.relationship; if (!relationship?.id) { setError('O vínculo não está disponível para encerramento.'); return } try { await repo.revokeRelationship(relationship.id); navigate('/professional/students', { replace: true }) } catch { setError('Não foi possível encerrar o vínculo.') } }
  if (busy) return <div className="narrow professional-page"><AppHeader title="Aluno" backTo="/professional/students" /><p role="status">Carregando aluno…</p></div>
  if (!client || !detail) return <div className="narrow professional-page"><AppHeader title="Aluno" backTo="/professional/students" /><p role="alert" className="error">{error || 'Aluno não encontrado.'}</p><Button onClick={() => navigate('/professional/students')}>Voltar para alunos</Button></div>
  const executions = detail.executions || []; const latestExecution = executions[0]
  return <div className="narrow professional-page professional-student-page"><AppHeader title={client.displayName} subtitle={`${client.programTitle || 'Sem programa ativo'} · vínculo ativo`} backTo="/professional/students" /><ProfessionalWorkspaceNav />{error && <p role="alert" className="error">{error}</p>}<div className="seg" role="tablist" aria-label="Detalhe do aluno">{TABS.map(([value, label]) => <button type="button" role="tab" aria-selected={tab === value} className={tab === value ? 'on' : ''} key={value} onClick={() => setTab(value)}>{label}</button>)}</div>
    {tab === 'summary' && <Section title="Resumo"><div className="dashboard-stats"><div className="card"><strong>{client.programTitle || '—'}</strong><span>programa atual</span></div><div className="card"><strong>{latestExecution ? statusLabel(latestExecution.status) : '—'}</strong><span>último treino</span></div><div className="card"><strong>{executions.length}</strong><span>execuções</span></div></div><p className="muted small">Vínculo criado em {String(client.relationshipCreatedAt || '').slice(0, 10) || '—'}.</p></Section>}
    {tab === 'training' && <Section title="Gerenciar treino"><p>{client.programTitle || 'Nenhum programa enviado'}</p><label>Enviar nova versão<select aria-label="Versão do programa" value={versionId} onChange={event => setVersionId(event.target.value)}><option value="">Selecione uma versão</option>{versions.map(version => <option key={version.id} value={version.id}>Versão {version.version_number}</option>)}</select></label><Button variant="primary" disabled={!versionId} onClick={assign}>Enviar versão</Button><Button onClick={() => navigate('/professional/programs')}>Abrir programas</Button></Section>}
    {tab === 'history' && <Section title="Histórico de treinos">{executions.length ? executions.map(item => <div className="card history-row" key={item.id}><strong>{item.day_key}</strong><span className="muted small">{statusLabel(item.status)} · {String(item.started_at || '').slice(0, 16).replace('T', ' ')}</span></div>) : <p className="muted">Nenhuma execução registrada.</p>}</Section>}
    {tab === 'relationship' && <Section title="Vínculo"><p>Profissional e aluno estão vinculados.</p><p className="muted small">O profissional pode acompanhar somente os programas e execuções deste vínculo.</p>{confirmRevoke ? <div className="danger-confirm"><span>Encerrar vínculo?</span><Button variant="danger" onClick={revoke}>Confirmar</Button><Button onClick={() => setConfirmRevoke(false)}>Cancelar</Button></div> : <Button variant="ghost" onClick={() => setConfirmRevoke(true)}>Encerrar vínculo</Button>}</Section>}
  </div>
}
