// @vitest-environment happy-dom
import React, { act } from 'react'
import { createRoot } from 'react-dom/client'
import { MemoryRouter, Routes, Route, Link } from 'react-router-dom'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ auth: { status: 'authenticated', user: { id: 's1' } }, repo: { studentProfessionalDetail: vi.fn(), revokeRelationship: vi.fn() }, replace: vi.fn(), start: vi.fn() }))
vi.mock('../auth/AuthProvider.jsx', () => ({ useAuth: () => mocks.auth }))
vi.mock('../lib/supabase-client.js', () => ({ getBrowserSupabaseClient: () => null }))
vi.mock('../lib/professional-workflow.js', () => ({ createProfessionalWorkflowRepository: () => mocks.repo }))
vi.mock('../store/useStore.js', () => ({ useStore: { getState: () => ({ S: {}, replaceState: mocks.replace }) } }))
vi.mock('../sheets.jsx', () => ({ startFlow: mocks.start }))
import StudentProfessionalDetail from './StudentProfessionalDetail.jsx'
const detail = id => ({ professional: { professionalId: id, professionalName: id === 'p1' ? 'Ana Silva' : 'João Reis', specialties: ['Força'], bio: 'Acompanhamento', cityRegion: 'São Paulo', registrationType: 'CREF', registrationNumber: '123' }, relationship: { id: `r-${id}`, status: 'active', linkedAt: '2026-09-01' }, materials: [{ assignmentId: `a-${id}`, title: `Programa ${id}`, status: 'replaced', versionNumber: 1, weeklyPlan: { monday: [{ exerciseId: 'squat', sets: 3, reps: 10 }] } }], executions: [{ id: 'e1', day_key: 'monday', status: 'completed', started_at: '2026-10-01', payload: {} }] })
let root, container
beforeEach(() => { vi.clearAllMocks(); mocks.repo.studentProfessionalDetail.mockImplementation(id => Promise.resolve(detail(id))); mocks.repo.revokeRelationship.mockResolvedValue({}); container = document.createElement('div'); document.body.append(container); root = createRoot(container) })
afterEach(async () => { await act(async () => root.unmount()); container.remove() })
const render = async path => act(async () => root.render(<MemoryRouter initialEntries={[path]}><Link to="/student/professionals/p2?section=training">Select João</Link><Routes><Route path="/student/professionals/:professionalId" element={<StudentProfessionalDetail />} /><Route path="/student/professionals" element={<p>Overview destination</p>} /></Routes></MemoryRouter>))
it('opens the history section directly with the recent window and comparison', async () => { await render('/student/professionals/p1?section=history'); expect(container.querySelector('a[aria-current="page"][href$="?section=history"]')).not.toBeNull(); expect(container.textContent).toContain('Até 100 execuções recentes'); expect(container.textContent).toContain('Prescrito'); expect(container.textContent).toContain('Realizado') })
it('requires explicit confirmation to end a relationship', async () => { await render('/student/professionals/p1?section=relationship'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Desvincular').click()); expect(mocks.repo.revokeRelationship).not.toHaveBeenCalled(); expect(container.textContent).toContain('Desvincular este profissional?'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Confirmar').click()); expect(mocks.repo.revokeRelationship).toHaveBeenCalledWith('r-p1'); expect(container.textContent).toContain('Overview destination') })
it('does not start or synchronize a historical material', async () => { await render('/student/professionals/p1?section=training&material=a-p1'); expect(container.textContent).toContain('Programa p1'); expect([...container.querySelectorAll('button')].some(x => x.textContent === 'Iniciar')).toBe(false); expect(mocks.replace).not.toHaveBeenCalled(); expect(mocks.start).not.toHaveBeenCalled() })
it('clears an earlier professional while the selected person is loading', async () => { await render('/student/professionals/p1?section=training'); let resolve; mocks.repo.studentProfessionalDetail.mockReturnValueOnce(new Promise(r => { resolve = r })); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Select João').click()); expect(container.textContent).not.toContain('Programa p1'); await act(async () => resolve(detail('p2'))); expect(container.textContent).toContain('João Reis'); expect(container.textContent).toContain('Programa p2'); expect(container.textContent).not.toContain('Programa p1') })
it('offers retry and return on selected-person failure', async () => { mocks.repo.studentProfessionalDetail.mockRejectedValue(new Error('offline')); await render('/student/professionals/p1'); expect(container.textContent).toContain('Não foi possível carregar este profissional.'); expect(container.textContent).toContain('Voltar para meus profissionais'); expect(container.textContent).toContain('Tentar novamente') })
it('does not force overview navigation when section changes during unlink', async () => { let resolve; mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await render('/student/professionals/p1?section=relationship'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Desvincular').click()); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Confirmar').click()); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Histórico').click()); await act(async () => resolve({})); expect(container.textContent).not.toContain('Overview destination'); expect(container.textContent).toContain('Até 100 execuções recentes') })
it('discards a delayed response for the earlier selected person', async () => { let resolve; mocks.repo.studentProfessionalDetail.mockReturnValueOnce(new Promise(r => { resolve = r })); await render('/student/professionals/p1?section=training'); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Select João').click()); await act(async () => resolve(detail('p1'))); expect(container.textContent).toContain('Programa p2'); expect(container.textContent).not.toContain('Programa p1') })
it('does not show another professional returned for this destination', async () => { mocks.repo.studentProfessionalDetail.mockResolvedValue(detail('p2')); await render('/student/professionals/p1'); expect(container.textContent).toContain('Profissional não encontrado.'); expect(container.textContent).not.toContain('João Reis') })
it('shows the professional verification state accurately', async () => { const record = detail('p1'); record.professional.verificationStatus = 'verified'; mocks.repo.studentProfessionalDetail.mockResolvedValue(record); await render('/student/professionals/p1'); expect(container.textContent).toContain('Verificação: Verificado') })
