// @vitest-environment happy-dom
import React, { act } from 'react'
import { createRoot } from 'react-dom/client'
import { MemoryRouter, Routes, Route, Link, useLocation } from 'react-router-dom'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ auth: { status: 'authenticated', user: { id: 's1' } }, repo: { studentProfessionalDetail: vi.fn(), revokeRelationship: vi.fn() }, replace: vi.fn(), start: vi.fn(), state: {}, scopeToken: null }))
vi.mock('../auth/AuthProvider.jsx', () => ({ useAuth: () => mocks.auth }))
vi.mock('../lib/supabase-client.js', () => ({ getBrowserSupabaseClient: () => null }))
vi.mock('../lib/professional-workflow.js', () => ({ createProfessionalWorkflowRepository: () => mocks.repo }))
vi.mock('../store/useStore.js', () => ({ useStore: { getState: () => ({ S: mocks.state, replaceState: mocks.replace, getScopeToken: () => ({ ...mocks.scopeToken }), isScopeCurrent: token => token.scope === mocks.scopeToken.scope && token.generation === mocks.scopeToken.generation }) } }))
vi.mock('../sheets.jsx', () => ({ startFlow: mocks.start }))
import StudentProfessionalDetail from './StudentProfessionalDetail.jsx'
import { assignedPlanToState } from '../lib/assigned-program.js'
const detail = id => ({ professional: { professionalId: id, professionalName: id === 'p1' ? 'Ana Silva' : 'João Reis', specialties: ['Força'], bio: 'Acompanhamento', cityRegion: 'São Paulo', registrationType: 'CREF', registrationNumber: '123' }, relationship: { id: `r-${id}`, status: 'active', linkedAt: '2026-09-01' }, materials: [{ assignmentId: `a-${id}`, title: `Programa ${id}`, status: 'replaced', versionNumber: 1, weeklyPlan: { monday: [{ exerciseId: 'squat', sets: 3, reps: 10 }] } }], executions: [{ id: 'e1', day_key: 'monday', status: 'completed', started_at: '2026-10-01', payload: {} }] })
let root, container
beforeEach(() => { vi.clearAllMocks(); mocks.auth = { status: 'authenticated', user: { id: 's1' } }; mocks.scopeToken = { scope: { kind: 'account', userId: 's1' }, generation: 1 }; mocks.state = {}; mocks.replace.mockImplementation(value => { mocks.state = value }); mocks.repo.studentProfessionalDetail.mockImplementation(id => Promise.resolve(detail(id))); mocks.repo.revokeRelationship.mockResolvedValue({}); container = document.createElement('div'); document.body.append(container); root = createRoot(container) })
afterEach(async () => { await act(async () => root.unmount()); container.remove() })
function CurrentRoute() { const location = useLocation(); return <span data-route>{location.pathname}{location.search}</span> }
const render = async path => act(async () => root.render(<MemoryRouter initialEntries={[path]}><CurrentRoute /><Link to="/student/professionals/p2?section=training">Select João</Link><Routes><Route path="/student/professionals/:professionalId" element={<StudentProfessionalDetail />} /><Route path="/student/professionals/materials" element={<p>Materials destination</p>} /><Route path="/student/professionals" element={<p>Overview destination</p>} /></Routes></MemoryRouter>))
it('opens the history section directly with the recent window and comparison', async () => { await render('/student/professionals/p1?section=history'); expect(container.querySelector('a[aria-current="page"][href$="?section=history"]')).not.toBeNull(); expect(container.textContent).toContain('Até 100 execuções recentes'); expect(container.textContent).toContain('Prescrito'); expect(container.textContent).toContain('Realizado') })
it('requires explicit confirmation to end a relationship', async () => { await render('/student/professionals/p1?section=relationship'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Desvincular').click()); expect(mocks.repo.revokeRelationship).not.toHaveBeenCalled(); expect(container.textContent).toContain('Desvincular este profissional?'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Confirmar').click()); expect(mocks.repo.revokeRelationship).toHaveBeenCalledWith('r-p1'); expect(container.textContent).toContain('Overview destination') })
it('does not start or synchronize a historical material', async () => { await render('/student/professionals/p1?section=training&material=a-p1'); expect(container.textContent).toContain('Programa p1'); expect([...container.querySelectorAll('button')].some(x => x.textContent === 'Iniciar')).toBe(false); expect(mocks.replace).not.toHaveBeenCalled(); expect(mocks.start).not.toHaveBeenCalled() })
it('clears an earlier professional while the selected person is loading', async () => { await render('/student/professionals/p1?section=training'); let resolve; mocks.repo.studentProfessionalDetail.mockReturnValueOnce(new Promise(r => { resolve = r })); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Select João').click()); expect(container.textContent).not.toContain('Programa p1'); await act(async () => resolve(detail('p2'))); expect(container.textContent).toContain('João Reis'); expect(container.textContent).toContain('Programa p2'); expect(container.textContent).not.toContain('Programa p1') })
it('offers retry and return on selected-person failure', async () => { mocks.repo.studentProfessionalDetail.mockRejectedValue(new Error('offline')); await render('/student/professionals/p1'); expect(container.textContent).toContain('Não foi possível carregar este profissional.'); expect(container.textContent).toContain('Voltar para meus profissionais'); expect(container.textContent).toContain('Tentar novamente') })
it('does not force overview navigation when section changes during unlink', async () => { let resolve; mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await render('/student/professionals/p1?section=relationship'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Desvincular').click()); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Confirmar').click()); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Histórico').click()); await act(async () => resolve({})); expect(container.textContent).not.toContain('Overview destination'); expect(container.textContent).toContain('Até 100 execuções recentes') })
it('discards a delayed response for the earlier selected person', async () => { let resolve; mocks.repo.studentProfessionalDetail.mockReturnValueOnce(new Promise(r => { resolve = r })); await render('/student/professionals/p1?section=training'); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Select João').click()); await act(async () => resolve(detail('p1'))); expect(container.textContent).toContain('Programa p2'); expect(container.textContent).not.toContain('Programa p1') })
it('does not show another professional returned for this destination', async () => { mocks.repo.studentProfessionalDetail.mockResolvedValue(detail('p2')); await render('/student/professionals/p1'); expect(container.textContent).toContain('Profissional não encontrado.'); expect(container.textContent).not.toContain('João Reis') })
it('shows the professional verification state accurately', async () => { const record = detail('p1'); record.professional.verificationStatus = 'verified'; mocks.repo.studentProfessionalDetail.mockResolvedValue(record); await render('/student/professionals/p1'); expect(container.textContent).toContain('Verificação: Verificado') })
const activeRecord = () => { const record = detail('p1'); record.materials[0].status = 'active'; return record }
const localAssignedState = (assignmentId = 'a-p1', versionId = 'v1') => assignedPlanToState({ routines: [{ id: 'personal-r' }], week: {}, workouts: [{ id: 'personal-history' }] }, { id: versionId, weekly_plan: { monday: [{ exerciseId: 'squat', sets: 3 }] } }, { id: assignmentId })
it('reconciles the revoked assigned plan even when the section changes and detail becomes unavailable', async () => {
  let resolve; mocks.state = localAssignedState(); const assignedId = mocks.state.week[1]; mocks.state.week[2] = 'personal-r'; mocks.state.dayPlan = { '2026-10-05': assignedId, '2026-10-06': 'personal-r' }; mocks.repo.studentProfessionalDetail.mockResolvedValueOnce(activeRecord()).mockResolvedValueOnce(null); mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await render('/student/professionals/p1?section=relationship'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Desvincular').click()); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Confirmar').click()); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Histórico').click()); await act(async () => resolve({})); expect(mocks.state.assignedProgram).toBeNull(); expect(mocks.state.routines).toEqual([{ id: 'personal-r' }]); expect(mocks.state.week).toEqual({ 2: 'personal-r' }); expect(mocks.state.dayPlan).toEqual({ '2026-10-06': 'personal-r' }); expect(mocks.state.workouts).toEqual([{ id: 'personal-history' }]); expect(container.querySelector('[data-route]').textContent).toBe('/student/professionals/p1?section=history'); expect(container.textContent).toContain('Profissional não encontrado.'); expect(container.textContent).not.toContain('Overview destination')
})
it('preserves a concurrent legitimate assignment when the earlier professional unlink completes', async () => {
  let resolve; mocks.state = localAssignedState(); mocks.repo.studentProfessionalDetail.mockResolvedValue(activeRecord()); mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await render('/student/professionals/p1?section=relationship'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Desvincular').click()); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Confirmar').click()); mocks.state = localAssignedState('new-assignment', 'new-version'); const concurrent = structuredClone(mocks.state); await act(async () => [...container.querySelectorAll('a')].find(x => x.textContent === 'Histórico').click()); await act(async () => resolve({})); expect(mocks.state).toEqual(concurrent); expect(mocks.replace).not.toHaveBeenCalled()
})
it('does not clear the next account state when an earlier unlink finishes', async () => {
  let resolve; mocks.state = localAssignedState(); mocks.repo.studentProfessionalDetail.mockResolvedValue(activeRecord()); mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await render('/student/professionals/p1?section=relationship'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Desvincular').click()); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Confirmar').click()); mocks.auth = { status: 'authenticated', user: { id: 's2' } }; mocks.scopeToken = { scope: { kind: 'account', userId: 's2' }, generation: 2 }; mocks.state = localAssignedState(); await render('/student/professionals/p1?section=relationship'); const nextAccount = structuredClone(mocks.state); await act(async () => resolve({})); expect(mocks.state).toEqual(nextAccount); expect(mocks.replace).not.toHaveBeenCalled(); expect(container.textContent).not.toContain('Overview destination')
})
const beginUnlink = async () => { await render('/student/professionals/p1?section=relationship'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Desvincular').click()); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Confirmar').click()) }
const openMaterials = async () => act(async () => container.querySelector('a[href="/student/professionals/materials"]').click())
it('reconciles a successful unlink after same-account navigation unmounts the person workspace', async () => {
  let resolve; mocks.state = localAssignedState(); mocks.state.week[2] = 'personal-r'; mocks.repo.studentProfessionalDetail.mockResolvedValue(activeRecord()); mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await beginUnlink(); await openMaterials(); expect(container.textContent).toContain('Materials destination'); expect(mocks.state.assignedProgram.assignmentId).toBe('a-p1'); await act(async () => resolve({})); expect(mocks.state.assignedProgram).toBeNull(); expect(mocks.state.routines).toEqual([{ id: 'personal-r' }]); expect(mocks.state.week).toEqual({ 2: 'personal-r' }); expect(container.querySelector('[data-route]').textContent).toBe('/student/professionals/materials'); expect(container.textContent).not.toContain('Overview destination')
})
it('does not reconcile another account with a coincidentally identical assignment after unmount', async () => {
  let resolve; mocks.state = localAssignedState(); mocks.repo.studentProfessionalDetail.mockResolvedValue(activeRecord()); mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await beginUnlink(); await openMaterials(); mocks.auth = { status: 'authenticated', user: { id: 's2' } }; mocks.scopeToken = { scope: { kind: 'account', userId: 's2' }, generation: 2 }; mocks.state = localAssignedState(); const nextAccount = structuredClone(mocks.state); await act(async () => resolve({})); expect(mocks.state).toEqual(nextAccount); expect(mocks.replace).not.toHaveBeenCalled(); expect(container.textContent).toContain('Materials destination')
})
it('does not reconcile an initiating user whose local store belongs to another caller', async () => {
  let resolve; mocks.scopeToken = { scope: { kind: 'account', userId: 's2' }, generation: 1 }; mocks.state = localAssignedState(); mocks.repo.studentProfessionalDetail.mockResolvedValue(activeRecord()); mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await beginUnlink(); const wrongScope = structuredClone(mocks.state); await act(async () => resolve({})); expect(mocks.state).toEqual(wrongScope); expect(mocks.replace).not.toHaveBeenCalled()
})
it('preserves a legitimate replacement while unlink finishes after same-account unmount', async () => {
  let resolve; mocks.state = localAssignedState(); mocks.repo.studentProfessionalDetail.mockResolvedValue(activeRecord()); mocks.repo.revokeRelationship.mockReturnValueOnce(new Promise(r => { resolve = r })); await beginUnlink(); await openMaterials(); mocks.state = localAssignedState('new-assignment', 'new-version'); const concurrent = structuredClone(mocks.state); await act(async () => resolve({})); expect(mocks.state).toEqual(concurrent); expect(mocks.replace).not.toHaveBeenCalled(); expect(container.textContent).toContain('Materials destination')
})
