// @vitest-environment happy-dom
import React, { act } from 'react'
import { createRoot } from 'react-dom/client'
import { MemoryRouter, Routes, Route } from 'react-router-dom'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ auth: {}, repo: { studentProfessionals: vi.fn(), assignments: vi.fn(), assignedPrograms: vi.fn(), studentOverview: vi.fn(), version: vi.fn() }, replace: vi.fn(), start: vi.fn(), state: {} }))
vi.mock('../auth/AuthProvider.jsx', () => ({ useAuth: () => mocks.auth }))
vi.mock('../lib/supabase-client.js', () => ({ getBrowserSupabaseClient: () => null }))
vi.mock('../lib/professional-workflow.js', () => ({ createProfessionalWorkflowRepository: () => mocks.repo }))
vi.mock('../store/useStore.js', () => ({ useStore: { getState: () => ({ S: mocks.state, replaceState: mocks.replace }) } }))
vi.mock('../sheets.jsx', () => ({ startFlow: (...args) => mocks.start(...args) }))
import StudentProfessionals from './StudentProfessionals.jsx'
let root, container
beforeEach(() => { vi.clearAllMocks(); mocks.auth = { status: 'authenticated', user: { id: 's1' } }; mocks.state = { routines: [] }; mocks.repo.studentProfessionals.mockResolvedValue([]); mocks.repo.assignments.mockResolvedValue([]); mocks.repo.assignedPrograms.mockResolvedValue([]); mocks.repo.studentOverview.mockResolvedValue({}); container = document.createElement('div'); document.body.append(container); root = createRoot(container) })
afterEach(async () => { await act(async () => root.unmount()); container.remove() })
const render = async (path = '/student/professionals') => act(async () => root.render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/student/professionals" element={<StudentProfessionals />} /><Route path="/student/professionals/add" element={<p>Add destination</p>} /></Routes></MemoryRouter>))
it('names each linked professional and gives separate add and materials links', async () => { mocks.repo.studentProfessionals.mockResolvedValue([{ professionalId: 'p1', professionalName: 'Ana Silva', activeProgramTitle: 'Força' }, { professionalId: 'p2', professionalName: 'João Reis', activeProgramTitle: 'Corrida' }]); await render(); expect(container.textContent).toContain('Ana Silva'); expect(container.textContent).toContain('João Reis'); expect(container.querySelector('a[href="/student/professionals/p2"]').textContent).toContain('João Reis'); expect(container.querySelector('input')).toBeNull() })
it('shows an actionable empty state', async () => { await render(); expect(container.textContent).toContain('Você ainda não possui profissionais vinculados.'); expect(container.querySelector('a[href="/student/professionals/add"]')).not.toBeNull() })
it('preserves a code-bearing entry in the add destination', async () => { await render('/student/professionals?code=AB12'); expect(container.textContent).toContain('Add destination'); expect(mocks.repo.studentProfessionals).not.toHaveBeenCalled() })
it('shows an error and retries the summary request', async () => { mocks.repo.studentProfessionals.mockRejectedValueOnce(new Error('offline')); await render(); expect(container.querySelector('[role="alert"]').textContent).toContain('Não foi possível carregar seus profissionais.'); await act(async () => [...container.querySelectorAll('button')].find(x => x.textContent === 'Tentar novamente').click()); expect(mocks.repo.studentProfessionals).toHaveBeenCalledTimes(2) })
it('renders loading and discards an earlier account response and synchronization', async () => { let resolve; mocks.repo.studentProfessionals.mockReturnValueOnce(new Promise(r => { resolve = r })); await render(); expect(container.textContent).toContain('Carregando…'); mocks.auth = { status: 'authenticated', user: { id: 's2' } }; await render(); await act(async () => resolve([{ professionalId: 'p1', professionalName: 'Wrong account' }])); expect(container.textContent).not.toContain('Wrong account'); expect(mocks.replace).not.toHaveBeenCalled() })
it('synchronizes only the current active assignment', async () => { const rows = [{ id: 'a1', student_user_id: 's1', professional_user_id: 'p1', status: 'active', version_id: 'v1', created_at: '2026-10-01' }]; mocks.repo.assignments.mockResolvedValue(rows); mocks.repo.assignedPrograms.mockResolvedValue(rows); mocks.repo.studentProfessionals.mockResolvedValue([{ professionalId: 'p1', professionalName: 'Ana Silva' }]); mocks.repo.version.mockResolvedValue({ id: 'v1', weekly_plan: { monday: [{ exerciseId: 'squat', sets: 3 }] } }); await render(); expect(mocks.replace).toHaveBeenCalledWith(expect.objectContaining({ assignedProgram: expect.objectContaining({ assignmentId: 'a1', versionId: 'v1' }) })) })
it('does not leave anonymous or stalled authentication loading', async () => { mocks.auth = { status: 'anonymous', user: null }; await render(); expect(container.textContent).toContain('Entre na sua conta para acessar seus profissionais.'); expect(mocks.repo.studentProfessionals).not.toHaveBeenCalled(); mocks.auth = { status: 'initializing', user: null }; const timer = vi.spyOn(window, 'setTimeout').mockImplementation(fn => { fn(); return 1 }); await render(); expect(container.textContent).toContain('Não foi possível confirmar sua sessão. Tente novamente.'); timer.mockRestore() })
it('starts only a routine belonging to the synchronized active assignment', async () => {
  const plan = { monday: [{ exerciseId: 'squat', sets: 3 }] }
  const rows = [{ id: 'a1', student_user_id: 's1', status: 'active', professional_user_id: 'p1', version_id: 'v1' }]
  mocks.repo.studentProfessionals.mockResolvedValue([{ professionalId: 'p1', professionalName: 'Ana Silva' }]); mocks.repo.assignments.mockResolvedValue(rows); mocks.repo.assignedPrograms.mockResolvedValue(rows); mocks.repo.version.mockResolvedValue({ id: 'v1', weekly_plan: plan }); mocks.repo.studentOverview.mockResolvedValue({ assignment: { id: 'a1' }, program: { title: 'Força' }, professional: { id: 'p1', name: 'Ana Silva' }, version: { id: 'v1', weeklyPlan: plan } }); await render()
  const button = [...container.querySelectorAll('button')].find(x => x.textContent === 'Iniciar'); expect(button).toBeDefined()
  mocks.state = { assignedProgram: { assignmentId: 'a1', versionId: 'v1' }, week: { 1: 'assigned-r1' }, routines: [{ id: 'assigned-r1', assignmentId: 'a1' }] }; await act(async () => button.click()); expect(mocks.start).toHaveBeenCalledWith('assigned-r1')
  mocks.start.mockClear(); mocks.state.assignedProgram.assignmentId = 'other-assignment'; await act(async () => button.click()); expect(mocks.start).not.toHaveBeenCalled()
})
it('clears a synchronized professional plan when there is no active assignment', async () => { mocks.state = { assignedProgram: { assignmentId: 'old' }, routines: [{ id: 'old', assigned: true }], week: {} }; await render(); expect(mocks.replace).toHaveBeenCalled(); expect(mocks.replace.mock.calls[0][0].assignedProgram).toBeNull() })
it('does not show a current program under a different professional identity', async () => { const rows = [{ id: 'a1', status: 'active', student_user_id: 's1', professional_user_id: 'p1', version_id: 'v1' }]; mocks.repo.studentProfessionals.mockResolvedValue([{ professionalId: 'p1', professionalName: 'Ana Silva' }]); mocks.repo.assignments.mockResolvedValue(rows); mocks.repo.assignedPrograms.mockResolvedValue(rows); mocks.repo.version.mockResolvedValue({ id: 'v1', weekly_plan: {} }); mocks.repo.studentOverview.mockResolvedValue({ assignment: { id: 'a1' }, professional: { id: 'p2', name: 'João Reis' }, program: { title: 'Wrong professional program' }, version: { id: 'v1', weeklyPlan: {} } }); await render(); expect(container.textContent).not.toContain('Wrong professional program'); expect(container.textContent).not.toContain('João Reis') })
it('never adopts a newer issued assignment when the caller has no received active program', async () => {
  mocks.repo.assignments.mockResolvedValue([{ id: 'issued', student_user_id: 'another-student', professional_user_id: 's1', version_id: 'issued-v', status: 'active', created_at: '2026-10-05' }]); mocks.repo.assignedPrograms.mockResolvedValue([]); mocks.repo.version.mockResolvedValue({ id: 'issued-v', weekly_plan: { monday: [{ exerciseId: 'squat' }] } }); mocks.state = { assignedProgram: { assignmentId: 'obsolete', versionId: 'old-v' }, routines: [{ id: 'old-r', assigned: true }, { id: 'personal-r' }], week: { 1: 'old-r', 2: 'personal-r' } }
  await render(); expect(mocks.repo.version).not.toHaveBeenCalled(); expect(mocks.replace).toHaveBeenCalledWith(expect.objectContaining({ assignedProgram: null, routines: [{ id: 'personal-r' }], week: { 2: 'personal-r' } })); expect(mocks.repo.assignedPrograms).toHaveBeenCalledWith('s1'); expect(mocks.repo.assignments).not.toHaveBeenCalled()
})
it('synchronizes the caller received program even when a newer issued assignment is visible', async () => {
  const received = { id: 'received', student_user_id: 's1', professional_user_id: 'p1', version_id: 'received-v', status: 'active', created_at: '2026-10-01' }; const issued = { id: 'issued', student_user_id: 'another-student', professional_user_id: 's1', version_id: 'issued-v', status: 'active', created_at: '2026-10-05' }
  mocks.repo.assignments.mockResolvedValue([issued, received]); mocks.repo.assignedPrograms.mockResolvedValue([received]); mocks.repo.studentProfessionals.mockResolvedValue([{ professionalId: 'p1', professionalName: 'Ana Silva' }]); mocks.repo.version.mockImplementation(id => Promise.resolve({ id, weekly_plan: { monday: [{ exerciseId: 'squat' }] } })); await render(); expect(mocks.repo.version).toHaveBeenCalledWith('received-v'); expect(mocks.replace).toHaveBeenCalledWith(expect.objectContaining({ assignedProgram: expect.objectContaining({ assignmentId: 'received', versionId: 'received-v' }) })); expect(mocks.repo.assignments).not.toHaveBeenCalled()
})
it('guards synchronization against mismatched caller or unlinked professional rows', async () => { const rows = [{ id: 'wrong-caller', student_user_id: 's2', professional_user_id: 'p1', version_id: 'v1', status: 'active' }, { id: 'unlinked', student_user_id: 's1', professional_user_id: 'p2', version_id: 'v2', status: 'active' }]; mocks.repo.assignments.mockResolvedValue(rows); mocks.repo.assignedPrograms.mockResolvedValue(rows); mocks.repo.studentProfessionals.mockResolvedValue([{ professionalId: 'p1', professionalName: 'Ana Silva' }]); mocks.repo.version.mockResolvedValue({ id: 'v1', weekly_plan: { monday: [{ exerciseId: 'squat' }] } }); await render(); expect(mocks.repo.version).not.toHaveBeenCalled(); expect(mocks.replace).not.toHaveBeenCalled() })
