// English source equivalents for the Portuguese-authored professional workspace.
export default {
  "Gestão": "Management",
  "Exercícios": "Exercises",
  "Última alteração": "Last changed",
  "Atenção": "Attention",
  "Voltar ao FPP": "Back to FPP",
  "Retomar treino": "Resume workout",
  "Limpar busca": "Clear search",
  "Filtros": "Filters",
  "{0} treinos": "{0} workouts",
  "{0} alunos": "{0} students",
  "Ações de {0}": "Actions for {0}",
  "Abrir programas": "Open programs",
  "Adicionar exercício": "Add exercise",
  "Ajuste a busca ou troque o filtro.": "Adjust your search or change the filter.",
  "Aluno": "Student",
  "Aluno não encontrado.": "Student not found.",
  "Alunos": "Students",
  "Animação ainda não disponível para este exercício.": "Animation is not available for this exercise yet.",
  "Ao enviar, o programa ativo anterior será encerrado.": "Sending this program will end the previous active program.",
  "Arquivado": "Archived",
  "Arquivar": "Archive",
  "Arquivar encerra as atribuições ativas deste programa. As versões e o histórico serão preservados.": "Archiving ends active assignments for this program. Versions and history are preserved.",
  "Buscar aluno": "Search students",
  "Buscar execução": "Search workouts",
  "Buscar por dia ou status": "Search by day or status",
  "Buscar por nome": "Search by name",
  "Buscar programa": "Search programs",
  "Cancelar": "Cancel",
  "Carregando alunos…": "Loading students…",
  "Carregando aluno…": "Loading student…",
  "Carregando programas…": "Loading programs…",
  "Carregar mais": "Load more",
  "Comparar versões": "Compare versions",
  "Confirmar": "Confirm",
  "Confirmar arquivo": "Confirm archive",
  "Convidar aluno": "Invite student",
  "Convide seu primeiro aluno para começar a acompanhar treinos.": "Invite your first student to start tracking workouts.",
  "Copiar dia": "Copy day",
  "Dados do programa": "Program details",
  "Dados do programa salvos.": "Program details saved.",
  "Descanso (s)": "Rest (s)",
  "Descrição do programa": "Program description",
  "Descrição opcional": "Optional description",
  "Detalhe do aluno": "Student details",
  "Dia de destino": "Target day",
  "Dias do programa": "Program days",
  "Duplicar": "Duplicate",
  "Duplicar exercício {0}": "Duplicate exercise {0}",
  "Duração (s)": "Duration (s)",
  "Duração (min)": "Duration (min)",
  "Duração realizada (min)": "Actual duration (min)",
  "Editar programa semanal": "Edit weekly program",
  "Encerrar o vínculo também encerra as atribuições e o acesso profissional às execuções. O histórico pessoal do aluno é preservado.": "Ending the relationship also ends assignments and professional access to workouts. The student's personal history is preserved.",
  "Encerrar programa ativo": "End active program",
  "Encerrar vínculo": "End relationship",
  "Encerrar vínculo?": "End relationship?",
  "Enviar nova versão": "Send new version",
  "Enviar para aluno": "Send to student",
  "Esforço": "Effort",
  "Filtros de alunos": "Student filters",
  "Gerenciar treino": "Manage workout",
  "Grupo de superset": "Superset group",
  "Histórico de treinos": "Workout history",
  "Informe o nome do programa.": "Enter the program name.",
  "Mesmo grupo para exercícios em sequência": "Use the same group for consecutive exercises",
  "Monte uma nova versão; versões enviadas permanecem no histórico.": "Build a new version; sent versions remain in the history.",
  "Mover exercício {0} para baixo": "Move exercise {0} down",
  "Mover exercício {0} para cima": "Move exercise {0} up",
  "Nenhum aluno ainda": "No students yet",
  "Nenhum exercício corresponde à pesquisa.": "No exercises match your search.",
  "Nenhum exercício neste dia.": "No exercises on this day.",
  "Nenhum programa enviado": "No program sent",
  "Nenhum resultado": "No results",
  "Nenhum treino registrado": "No workouts recorded",
  "Nenhuma execução registrada.": "No workouts recorded.",
  "Nenhuma pendência identificada.": "No issues identified.",
  "Nenhuma série realizada recebida.": "No completed sets received.",
  "Nome do programa": "Program name",
  "Notas": "Notes",
  "Nova versão publicada.": "New version published.",
  "Novo programa": "New program",
  "Não foi possível atualizar o programa.": "Could not update the program.",
  "Não foi possível carregar este aluno.": "Could not load this student.",
  "Não foi possível carregar os alunos.": "Could not load the students.",
  "Não foi possível carregar os programas.": "Could not load the programs.",
  "Não foi possível criar o programa.": "Could not create the program.",
  "Não foi possível encerrar o programa.": "Could not end the program.",
  "Não foi possível encerrar o vínculo.": "Could not end the relationship.",
  "Não foi possível enviar esta versão.": "Could not send this version.",
  "Não foi possível publicar. Seu rascunho foi mantido; tente novamente.": "Could not publish. Your draft was preserved; try again.",
  "Não foi possível salvar os dados. Seu rascunho foi mantido.": "Could not save the details. Your draft was preserved.",
  "Pesquisar exercício": "Search exercises",
  "Pesquisar por nome, músculo ou equipamento": "Search by name, muscle or equipment",
  "Pessoas com vínculo ativo": "People with an active relationship",
  "Prescrito": "Prescribed",
  "Prescrição não disponível nesta execução.": "Prescription unavailable for this workout.",
  "Prescrições e versões reutilizáveis": "Reusable prescriptions and versions",
  "Profissional e aluno estão vinculados.": "Professional and student are linked.",
  "Programa criado.": "Program created.",
  "Programas": "Programs",
  "Programas ({0})": "Programs ({0})",
  "Rascunho recuperado.": "Draft restored.",
  "Realizado": "Completed",
  "Remover": "Remove",
  "Restaurar": "Restore",
  "Resumo": "Summary",
  "Salvar dados do programa": "Save program details",
  "Selecionar exercício": "Select exercise",
  "Selecione o aluno para revisar e enviar a versão escolhida.": "Select a student to review and send the chosen version.",
  "Selecione uma versão": "Select a version",
  "Sem descrição": "No description",
  "Sem esforço prescrito": "No prescribed effort",
  "Sem programa ativo": "No active program",
  "Sem programa, último treino abandonado ou 7 dias sem treinar. Treinos abertos há mais de 24 horas também aparecem aqui.": "No program, last workout abandoned, or no workout in 7 days. Workouts open for over 24 hours also appear here.",
  "Sem versão publicada": "No published version",
  "Substituiu {0}": "Replaced {0}",
  "Série {0}": "Set {0}",
  "Séries concluídas": "Completed sets",
  "Tentar novamente": "Try again",
  "Tipo de execução": "Execution type",
  "Todos os exercícios disponíveis para prescrição.": "All exercises available for prescription.",
  "Trocar dias": "Swap days",
  "Unidade": "Unit",
  "Ver animação de {0}": "View animation for {0}",
  "Ver todos os alunos": "View all students",
  "Versão do programa": "Program version",
  "Versão {0}": "Version {0}",
  "Versão {0} · {1} versão(ões)": "Version {0} · {1} version(s)",
  "Voltar para alunos": "Back to students",
  "Vínculo": "Relationship",
  "Vínculo criado em {0}.": "Relationship created on {0}.",
  "execuções": "workouts",
  "programa atual": "current program",
  "{0} aluno(s)": "{0} student(s)",
  "{0} exercício(s) encontrado(s)": "{0} exercise(s) found",
  "{0} · vínculo ativo": "{0} · active relationship",
  "{0} · {1} exercício(s)": "{0} · {1} exercise(s)",
  "último treino": "last workout",
  "Pendente": "Pending",
  "Ativo": "Active",
  "Revogado": "Revoked",
  "Concluído": "Completed",
  "Em andamento": "In progress",
  "Abandonado": "Abandoned",
  "Substituído": "Replaced",
  "Desconhecido": "Unknown",
  "Último treino abandonado": "Last workout abandoned",
  "Treino em andamento há mais de 24 horas": "Workout in progress for over 24 hours",
  "Sem treino há 7 dias": "No workout in 7 days",
  "Nenhum treino desde o vínculo há 7 dias": "No workout since linking 7 days ago",
  "Séries": "Sets",
  "Carga": "Load",
  "Velocidade (km/h)": "Speed (km/h)",
  "Domingo": "Sunday",
  "Segunda": "Monday",
  "Terça": "Tuesday",
  "Quarta": "Wednesday",
  "Quinta": "Thursday",
  "Sexta": "Friday",
  "Sábado": "Saturday",
  "Aplicar progressão sugerida": "Apply suggested progression",
  "Restaurar prescrição": "Restore prescription",
  "Nenhuma execução recebida ainda.": "No workouts received yet.",
  "Convide alunos para criar um vínculo": "Invite students to establish a relationship",
  "Crie um único convite e compartilhe o mesmo código ou link. O vínculo só nasce depois que o aluno confirmar.": "Create one invitation and share its code or link. The relationship begins when the student confirms.",
  "Convite Fit Pro Player": "Fit Pro Player invitation",
  "Compartilhar": "Share",
  "Sua conta não possui a capability profissional.": "Your account does not have professional access.",
  "Ative a área profissional para enviar treinos, gerar convites e acompanhar seus alunos.": "Activate the professional area to send workouts, create invitations and track your students.",
  "Tipo de registro": "Registration type",
  "Adicione uma apresentação curta.": "Add a short introduction.",
  "A conexão demorou mais que o esperado.": "The connection took longer than expected.",
  "Adicionar profissional": "Add professional",
  "Continuar": "Continue",
  "Convite inválido ou expirado.": "Invalid or expired invitation.",
  "Código do profissional": "Professional code",
  "Desde {0}": "Since {0}",
  "Desvincular": "Unlink",
  "Desvincular este profissional?": "Unlink this professional?",
  "Digite o código recebido e confira o perfil antes de vincular.": "Enter the code you received and review the profile before linking.",
  "Entre na sua conta para acessar seus profissionais.": "Sign in to access your professionals.",
  "Ex.: A1B2C3D4E5": "Example: A1B2C3D4E5",
  "Meus profissionais": "My professionals",
  "Não foi possível aceitar este convite.": "Could not accept this invitation.",
  "Não foi possível confirmar sua sessão. Tente novamente.": "Could not confirm your session. Try again.",
  "Não foi possível consultar o convite.": "Could not look up the invitation.",
  "Não foi possível iniciar o treino.": "Could not start the workout.",
  "Profissionais vinculados ({0})": "Linked professionals ({0})",
  "Profissional vinculado": "Professional linked",
  "Vincular a este profissional": "Link to this professional",
  "Você ainda não possui profissionais vinculados.": "You have no linked professionals yet.",
  "Vínculo aceito.": "Relationship accepted.",
  "Vínculos, convites e treinos recebidos": "Relationships, invitations and received workouts",
  "Ver": "View",
  "Editar": "Edit",
  "Perfil": "Profile",
  "Navegação da área profissional": "Professional area navigation",
  "Todos": "All",
  "Com programa": "With program",
  "Sem programa": "Without program",
  "Registro informado: {0} {1}": "Registration provided: {0} {1}",
  "Status do registro: {0}": "Registration status: {0}",
  "não verificado": "unverified",
  "Preview": "Preview",
  "Programa profissional": "Professional program",
  "Você ainda não recebeu um programa ativo.": "You have not received an active program yet.",
  "Programa atual": "Current program",
  "{0} · versão {1}": "{0} · version {1}",
  "Profissional": "Professional",
  "Atualizado em {0}": "Updated on {0}",
  "Ver prescrição completa": "View full prescription",
  "Próximos treinos": "Upcoming workouts",
  "{0} exercício(s)": "{0} exercise(s)",
  "Iniciar": "Start",
  "Nenhum treino programado.": "No workouts scheduled.",
  "Histórico": "History",
  "Não foi possível carregar a área profissional.": "Could not load the professional area.",
  "Esta área está disponível apenas para contas profissionais.": "This area is available only to professional accounts.",
  "Área profissional": "Professional area",
  "Uma visão rápida do seu trabalho": "A quick view of your work",
  "Carregando área profissional…": "Loading professional area…",
  "Visão geral": "Overview",
  "alunos ativos": "active students",
  "convites pendentes": "pending invitations",
  "sem programa": "without program",
  "programas": "programs",
  "Ações rápidas": "Quick actions",
  "Criar programa": "Create program",
  "Ver alunos": "View students",
  "Alunos que precisam de atenção": "Students needing attention",
  "Você ainda não possui alunos ativos.": "You have no active students yet.",
  "Convidar primeiro aluno": "Invite first student",
  "Atividade recente": "Recent activity",
  "Não foi possível carregar os convites.": "Could not load invitations.",
  "Convite criado. Compartilhe o código abaixo.": "Invitation created. Share the code below.",
  "Não foi possível criar o convite.": "Could not create the invitation.",
  "Convite revogado.": "Invitation revoked.",
  "Não foi possível revogar este convite.": "Could not revoke this invitation.",
  "Convites": "Invitations",
  "Carregando convites…": "Loading invitations…",
  "Nenhum convite pendente. Crie um convite para começar.": "No pending invitations. Create an invitation to get started.",
  "Código copiado.": "Code copied.",
  "Copiar código": "Copy code",
  "Link copiado.": "Link copied.",
  "Copiar link": "Copy link",
  "Revogar este convite?": "Revoke this invitation?",
  "Revogar": "Revoke",
  "Não foi possível carregar o perfil profissional.": "Could not load the professional profile.",
  "Não foi possível salvar agora. Verifique sua conexão.": "Could not save now. Check your connection.",
  "Informe seu nome profissional.": "Enter your professional name.",
  "Não foi possível criar o perfil profissional. Verifique sua conexão.": "Could not create the professional profile. Check your connection.",
  "Perfil profissional": "Professional profile",
  "Entre em uma conta para acessar o perfil profissional.": "Sign in to access the professional profile.",
  "Carregando…": "Loading…",
  "Tornar-se profissional": "Become a professional",
  "Crie seu perfil profissional": "Create your professional profile",
  "Nome profissional": "Professional name",
  "Especialidades": "Specialties",
  "Cidade/região": "City/region",
  "Número do registro": "Registration number",
  "Criando…": "Creating…",
  "Criar perfil profissional": "Create professional profile",
  "Modo do perfil": "Profile mode",
  "Sem perfil profissional": "No professional profile",
  "Especialidades:": "Specialties:",
  "Editar perfil": "Edit profile",
  "Salvar exige conexão. O status de verificação é controlado pelo sistema.": "Saving requires a connection. Verification status is managed by the system.",
  "Salvando…": "Saving…",
  "Salvar perfil": "Save profile",
  "N�o foi poss�vel encerrar o v�nculo.": "Unable to close the link.",
  "Programa arquivado.": "Program archived.",
  "Programa restaurado.": "Program restored.",
  "Criar nova versão": "Create new version",
  "Editar programa": "Edit program",
  "Nenhum resultado.": "No results.",
  "Crie seu primeiro programa semanal.": "Create your first weekly program.",
  "Prescrições iguais.": "Prescriptions are identical.",
  "Compare os exercícios, cargas e descansos antes de enviar uma nova versão.": "Compare exercises, weights and rest times before sending a new version.",
  "Versão anterior": "Previous version",
  "Versão nova": "New version",
  "Enviando…": "Sending…",
  "Enviar versão": "Send version",
  "Não foi possível carregar seus profissionais.": "Could not load your professionals.",
  "Adicione pelo menos um exercício antes de publicar.": "Add at least one exercise before publishing.",
  "Revise os exercícios e os valores informados.": "Review the exercises and values entered.",
  "Não foi possível salvar o rascunho neste dispositivo.": "Could not save the draft on this device.",
  "Rascunho salvo neste dispositivo.": "Draft saved on this device.",
  "Selecionado": "Selected",
  "Adicionar": "Add",
  "Publicando…": "Publishing…",
  "Publicar nova versão": "Publish new version",
  "A consulta do convite demorou mais que o esperado.": "The invitation lookup took longer than expected.",
  "Não foi possível consultar este convite.": "Could not look up this invitation.",
  "Vínculo criado.": "Relationship created.",
  "Não foi possível aceitar este convite. Ele pode ter expirado ou já ter sido utilizado.": "Could not accept this invitation. It may have expired or already been used.",
  "Convite profissional": "Professional invitation",
  "Confira antes de vincular": "Review before linking",
  "Convite indisponível": "Invitation unavailable",
  "Consultando convite…": "Looking up invitation…",
  "Verificação: {0}": "Verification: {0}",
  "Peça um novo código ao profissional.": "Ask the professional for a new code.",
  "Crie seu perfil para enviar treinos e convites": "Create your profile to send workouts and invitations",
  "Navegação dos meus profissionais": "My professionals navigation",
  "Materiais": "Materials",
  "Apresentação": "Introduction",
  "Atuação": "Practice",
  "Separe por vírgulas. Até 8 especialidades.": "Separate with commas. Up to 8 specialties.",
  "Registro profissional": "Professional registration",
  "Informe o código do convite.": "Enter the invitation code.",
  "Confira o perfil antes de aceitar o convite": "Review the profile before accepting the invitation",
  "Código do convite": "Invitation code",
  "Verificado": "Verified",
  "Em análise": "Under review",
  "Não aprovado": "Not approved",
  "Não verificado": "Unverified",
  "Ver treino recebido": "View received workout",
  "Próximo treino": "Next workout",
  "Perfil profissional criado.": "Professional profile created.",
  "Perfil salvo.": "Profile saved.",
  "Sua conta não tem acesso à edição profissional.": "Your account cannot edit professional details.",
  "Atualize sua apresentação e seus dados profissionais.": "Update your introduction and professional details.",
  "Sua apresentação para os alunos.": "Your introduction for students.",
  "Não informado": "Not provided",
  "Status do registro": "Registration status",
  "Acompanhe seus alunos e organize os próximos treinos.": "Track your students and organize upcoming workouts.",
  "programas disponíveis": "available programs",
  "Preparar próximos treinos": "Prepare upcoming workouts",
  "Entre na sua conta para continuar.": "Sign in to continue.",
  "Não foi possível carregar as versões.": "Could not load versions.",
  "Carregando versões…": "Loading versions…",
  "Programa": "Program",
  "Selecione um programa": "Select a program",
  "Encerrar programa ativo?": "End active program?",
  "Não foi possível compartilhar o convite. Tente novamente.": "Could not share the invitation. Try again.",
  "Novo convite": "New invitation",
  "Compartilhar convite": "Share invitation",
  "Pendentes ({0})": "Pending ({0})",
  "Crie um convite para começar.": "Create an invitation to get started.",
  "Criado em {0}": "Created on {0}",
  "Voltar para convites": "Back to invitations",
  "Programa não encontrado.": "Program not found.",
  "Voltar para programas": "Back to programs",
  "Versões publicadas": "Published versions",
  "Mais recente": "Latest",
  "Ver prescrição": "View prescription",
  "Status do programa": "Program status",
  "Pessoas que acompanham seu treino": "People supporting your training",
  "Vínculo ativo": "Active relationship",
  "Use o convite recebido para começar o acompanhamento.": "Use your invitation to start working with a professional.",
  "Materiais recebidos": "Received materials",
  "Consulte programas e prescrições de cada profissional.": "Browse each professional's programs and prescriptions.",
  "Ver materiais": "View materials",
  "Carregando profissional…": "Loading professional…",
  "Profissional não encontrado.": "Professional not found.",
  "Voltar para meus profissionais": "Back to my professionals",
  "Acompanhamento profissional": "Professional guidance",
  "Detalhe do profissional": "Professional details",
  "O profissional ainda não adicionou uma apresentação.": "The professional has not added an introduction yet.",
  "Localização": "Location",
  "Registro não informado.": "Registration not provided.",
  "Treino recebido": "Received workout",
  "Até 100 materiais recentes deste profissional.": "Up to 100 recent materials from this professional.",
  "Ver todos os materiais deste profissional": "View all materials from this professional",
  "Recebido em {0}": "Received on {0}",
  "Publicado em {0}": "Published on {0}",
  "Abrir programa atual": "Open current program",
  "Até 100 execuções recentes deste profissional.": "Up to 100 recent workouts from this professional.",
  "Desvincular encerra os programas deste profissional. Seu histórico pessoal é preservado.": "Unlinking ends this professional's programs. Your personal history is preserved.",
  "Programas e prescrições dos seus profissionais": "Programs and prescriptions from your professionals",
  "Até 100 materiais recentes por profissional com vínculo ativo.": "Up to 100 recent materials per linked professional.",
  "Carregando materiais…": "Loading materials…",
  "Ver profissional": "View professional",
  "Nenhum material recebido deste profissional.": "No materials received from this professional.",
  "Alunos, convites e programas": "Students, invitations and programs",
  "Arquivados": "Archived",
  "Convite não encontrado.": "Invitation not found.",
  "Disponíveis": "Available",
  "Disponível": "Available",
  "Gerar convite": "Create invitation",
  "Nenhum convite pendente.": "No pending invitations.",
  "Sem programas": "No programs",
  "Vínculo encerrado": "Relationship ended",
  "Vinculando…": "Linking…",
  "Não foi possível carregar este profissional.": "Could not load this professional.",
  "Treino": "Workout",
  "Encerrado": "Ended",
  "Material não encontrado nesta janela recente.": "Material not found among recent items.",
  "Desvinculando…": "Unlinking…",
  "Não foi possível carregar os materiais deste profissional.": "Could not load this professional's materials.",
  "Bio": "Bio",
  "Montar semana": "Plan the week",
  "Escolha o dia, adicione exercícios e ajuste a prescrição. Depois publique e envie ao aluno.": "Choose a day, add exercises and adjust the prescription. Then publish and send to the student.",
  "Opções avançadas": "Advanced options",
  "Substituir exercícios do dia?": "Replace this day’s exercises?",
  "Os exercícios de {0} serão substituídos pelos de {1}.": "The exercises for {0} will be replaced with those for {1}.",
  "Substituir dia": "Replace day",
  "Publicar salva uma versão do programa. O envio ao aluno é feito no próximo passo.": "Publishing saves a program version. Send it to the student in the next step.",
  "Use a seta para ver a animação e Adicionar para incluir no dia.": "Use the arrow to preview the animation and Add to include it in the day.",
  "Filtrar por músculo": "Filter by muscle",
  "Filtrar por equipamento": "Filter by equipment",
  "{0} exercício(s) no dia": "{0} exercise(s) in the day",
  "Editar prescrição": "Edit prescription",
  "Ações do exercício {0}": "Exercise {0} actions",
  "Nome do treino": "Workout name",
  "Concluir treino": "Finish workout",
  "Revisar semana": "Review week",
  "Publicar semana": "Publish week",
  "Objetivo": "Objective",
  "Treino não encontrado.": "Workout not found.",
  "Versão não encontrada.": "Version not found."
}
